server/main-project/build.gradle
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/controller/AnswerController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/dto/AnswerDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/entity/Answer.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/mapper/AnswerMapper.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/repository/AnswerRepository.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/service/AnswerService.java
server/main-project/src/main/java/seb42_main_026/mainproject/dto/MultiResponseDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/dto/PageInfo.java
server/main-project/src/main/java/seb42_main_026/mainproject/dto/SingleResponseDto.java

선생님들 확인 부탁드립니다
**_추가사항_**
1. build.gradle : dependency 추가
- mapstruct 1.5.3.
- validation
2. Dto(Global) : SingleResponseDto, MultiResponseDto, PageInfo
3. 답변(잔소리) : POST 메서드 구현 v1

Feat/be/answer -> be

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/controller/QuestionController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/dto/QuestionDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/entity/Question.java

1. Feat: Question Entity 구현
- Question 클래스 구현(연관관계 매핑 미적용)
2. Feat: QuestionController Stub data 적용
- QuestionDto 클래스 구현
- QuestionController 클래스 스텁 데이터 적용하여 구현(추후 실제 데이터 사용하도록 갱신)

Feat: Question & QuestionController 구현

---

server/main-project/.gitignore
server/main-project/src/main/java/seb42_main_026/mainproject/MainProjectApplication.java
server/main-project/src/main/java/seb42_main_026/mainproject/audit/Auditable.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/entity/Question.java

1. Feat: Auditable 추상 클래스 구현
- Auditable 추상 클래스 구현
- MainProjectApplication에서 @EnableJpaAuditing 추가
- Question 엔티티에서 Auditable 상속받아 사용

Feat: Auditable 추상 클래스 구현

---

server/main-project/src/main/java/seb42_main_026/mainproject/exception/CustomException.java
server/main-project/src/main/java/seb42_main_026/mainproject/exception/ErrorResponse.java
server/main-project/src/main/java/seb42_main_026/mainproject/exception/ExceptionCode.java
server/main-project/src/main/java/seb42_main_026/mainproject/exception/GlobalExceptionAdvice.java

Exception(2023.03.08. 수요일) 
- CustiomException 구현
- ErrorResponse 구현 
- ExceptionCode 구현
- GlobalExceptionAdvice 구현

feat: global exception 구현

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/controller/MemberController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/dto/MemberDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/entity/Member.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/mapper/MemberMapper.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/repository/MemberRepository.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/service/MemberService.java

Member 구현
- Member Controller
- Member Dto
- Member Entity
- Member Mapper
- Member Service

feat: 멤버 구현

---

server/main-project/src/main/java/seb42_main_026/mainproject/utils/CustomBeanUtils.java

1. Feat: 정보 수정 시 사용 가능한 CustomBeanUtils 클래스 구현
- patchMember, patchQuestion 같이 수정하는 메서드에서 사용 가능한 CustomBeanUtils 클래스 및 copyNonNullProperties 메서드 구현

Feat: 정보 수정 시 사용 가능한 CustomBeanUtils 클래스 구현

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/controller/QuestionController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/dto/QuestionDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/entity/Question.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/mapper/QuestionMapper.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/repository/QuestionRepository.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/service/QuestionService.java

1. Feat: Question 도메인 기본 컴포넌트 구현
2. Feat: 질문 작성 기능 구현

Feat: 질문 작성 기능 구현

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/controller/AnswerController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/dto/AnswerDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/entity/Answer.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/service/AnswerService.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/comment/controller/CommentController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/comment/dto/CommentDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/comment/entity/comment.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/comment/mapper/CommentMapper.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/comment/repository/CommentRepository.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/comment/service/CommentService.java
server/main-project/src/main/java/seb42_main_026/mainproject/exception/ExceptionCode.java

1. 지일님 코드 리뷰 반영
- 생성자 리팩토링
- annotation 추가
2. ExceptionCode Enum에 추가
- 'ANSWER_NOT_FOUND' 추가
3. Answer Patch 매서드 추가 v1
- 연관관계 매핑 및 다른 엔티티 메서드 추가 작성 필요

feat: 답변 수정기능 v1

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/tag/Tag.java

Feat: Tag 구현

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/like/controller/LikeController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/like/dto/LikeDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/like/entity/Like.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/like/mapper/LikeMapper.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/like/repository/LikeRepository.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/like/service/LikeService.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/controller/QuestionController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/dto/QuestionDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/entity/Question.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/mapper/QuestionMapper.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/repository/QuestionRepository.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/service/QuestionService.java
server/main-project/src/main/java/seb42_main_026/mainproject/dto/MultiResponseDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/exception/ExceptionCode.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/config/SecurityConfiguration.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/utils/UriCreator.java

Refactor: API 명세서 내용에 맞게 createQuestion 리팩토링

Refactor: API 명세서 내용에 맞게 createQuestion 리팩토링

---

server/main-project/src/main/java/seb42_main_026/mainproject/cloud/config/S3Config.java
server/main-project/src/main/java/seb42_main_026/mainproject/cloud/service/S3StorageService.java
server/main-project/src/main/java/seb42_main_026/mainproject/cloud/service/StorageService.java
server/main-project/src/main/java/seb42_main_026/mainproject/exception/StorageException.java

Global 패키지로 구성해서
S3 버킷,RDS 연결 후 주석처리 해제하고 쓰시면 됩니다!

Feat : MultiPart File 업로드 기능 (S3 연결 전까지 주석처리)

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/controller/AnswerController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/dto/AnswerDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/entity/Answer.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/mapper/AnswerMapper.java

feat: 조회 기능 #9

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/controller/MemberController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/service/MemberService.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/config/SecurityConfiguration.java

- MemberService updateScore 로직 테스트에 편하게 변경.

Fix: Member Controller Endpoint 수정 및 SecurityConfiguration 

---

client/src/App.tsx
client/src/components/BottomNav.tsx
client/src/components/TopNav.tsx
client/src/container/mypage/ProfileCard.tsx

fix : pathname에 따라 상단바 문구 변경

---

server/main-project/src/main/java/seb42_main_026/mainproject/security/Oauth2/OAuth2MemberSuccessHandler.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/config/SecurityConfiguration.java

- [FIx: Oauth2 redirect url](https://github.com/codestates-seb/seb42_main_026/commit/226fa4fd5d5aa1c52dd9864e038c1a443bc9fd87)

Fix: 토큰 클레임 수정

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/repository/QuestionRepository.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/service/QuestionService.java

Fix: 인기글 정렬 기준 변경
기존 - 1순위: 좋아요 순, 2순위: 오래된 질문 순
변경 - 1순위: 좋아요 순, 2순위: 답변 개수 순

Fix: 인기글 정렬 기준 변경

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/entity/Member.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/entity/Score.java
server/main-project/src/main/resources/application.yml

@AuthenticationPrincipal      적용 전까지 주석 처리
적용 후 주석 해제

Refactor: Index 사용하여 검색 성능 개선(주석처리)

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/controller/AnswerController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/dto/AnswerDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/answer/service/AnswerService.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/comment/controller/CommentController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/comment/service/CommentService.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/like/controller/LikeController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/like/dto/LikeDto.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/like/service/LikeService.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/controller/MemberController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/service/MemberService.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/controller/QuestionController.java
server/main-project/src/main/java/seb42_main_026/mainproject/domain/question/service/QuestionService.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/config/SecurityConfiguration.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/filter/JwtVerificationFilter.java

회원 아이디를 요청에서 제외함으로써 보안 개선
-> 토큰으로 회원 식별

Refactor: 전체 도메인 보안 개선

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/entity/Member.java
server/main-project/src/main/java/seb42_main_026/mainproject/exception/ErrorResponse.java
server/main-project/src/main/java/seb42_main_026/mainproject/exception/ExceptionCode.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/Oauth2/OAuth2MemberSuccessHandler.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/config/SecurityConfiguration.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/controller/JwtControlloer.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/filter/JwtAuthenticationFilter.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/filter/JwtVerificationFilter.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/jwt/JwtTokenizer.java
server/main-project/src/main/resources/application.yml

- Refresh 구현
- Conflict 해결
- Config 수정

Fix: yml 파일 정리

---

server/main-project/src/main/java/seb42_main_026/mainproject/domain/member/repository/RefreshRepository.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/Oauth2/OAuth2MemberSuccessHandler.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/controller/JwtController.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/filter/JwtAuthenticationFilter.java
server/main-project/src/main/java/seb42_main_026/mainproject/security/jwt/JwtTokenizer.java

날짜 조작을 위해 Java 8의 Instant 및 Duration 클래스 사용: Java 8에서는 java.time 패키지를 도입. 이 패키지는 날짜와 시간을 조작하는 더 편리하고 읽기 쉬운 방법을 제공.

Refactor: Calendar를 java.time 사용하도록 리팩토링
